apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-code-with-quarkus-hlc5
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-code-with-quarkus-hlc5
    app.kubernetes.io/part-of: test-rhtap-53-app
  name: devfile-sample-code-with-quarkus-hlc5
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: java-quarkus-app
      app.kubernetes.io/instance: devfile-sample-code-with-quarkus-hlc5
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: java-quarkus-app
        app.kubernetes.io/instance: devfile-sample-code-with-quarkus-hlc5
    spec:
      containers:
      - image: quay.io/redhat-user-workloads-stage/test-rhtap-53-tenant/test-rhtap-53-app/devfile-sample-code-with-quarkus-hlc5@sha256:da93a0dd8f2c38ae7f6193b69ed7341c0ce2a59dc83abd3d9cbfc285ff2d935e
        name: my-java-quarkus
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 100Mi
status: {}
